### ISSUE TITLE
電子を使用したテストの翻訳に関する問題

### ISSUE THREAD

**Issue by karuakun** [dotnet/AspNetCore.Docs.ja-jp#292]
電子を使用したテスト
Electronはフレームワーク名です、翻訳しないでください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1945dedd-e2b8-37c1-2676-e473498bcb30
* Version Independent ID: 631281cb-65db-3196-1a6a-da9b3f2e3fed
* Content: [ASP.NET Core での SameSite cookie の使用](https://docs.microsoft.com/ja-jp/aspnet/core/security/samesite?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/samesite.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/samesite.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @karuakun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Electronic testing
Electron is the framework name, do not translate.

@guardrex  what's the meta-data I use for `Electron`? Should I just `code fence it`? 

### Test with Electron

Versions of Electron include older versions of Chromium. For example, the version of Electron used by Teams is Chromium 66, which exhibits the older behavior. You must perform your own compatibility testing with the version of Electron your product uses. See [Supporting older browsers](#sob) in the following section.

**Comment by CeciAc** [comment]
@Rick-Anderson @guardrex there's no action on the loc team side since this is MT content
can we close this issue?

**Comment by guardrex** [comment]
Yes ...

https://github.com/dotnet/AspNetCore.Docs/pull/17207/files

... we're good. :+1:

**Comment by CeciAc** [comment]
@karuakun 
フィードバックとご提案をいただき、ありがとうございます。  
現在、ファイルはローカライズ処理中です。このアーティクルはまもなくリリースされます。
サポートいただきありがとうございます。 

敬具

Microsoft DOCS グローバル エクスペリエンス チーム
