### ISSUE TITLE
若干、誤字がありました

### ISSUE THREAD

**Issue by xyzpda** [dotnet/AspNetCore.Docs.ja-jp#293]
■オープンリダイレクト攻撃からの保護

既知の ULR 　→　既知の URL 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5c890a93-93f0-7492-a394-747055ff9471
* Version Independent ID: e0b6ad54-4a85-eae4-a4e2-8e4e7149089c
* Content: [ASP.NET Core でのオープンリダイレクト攻撃の防止](https://docs.microsoft.com/ja-jp/aspnet/core/security/preventing-open-redirects?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/preventing-open-redirects.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/preventing-open-redirects.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @xyzpda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@xyzpda 様:

投稿いただき、ありがとうございます。

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。

サポートいただきありがとうございます。

Microsoft DOCS グローバル エクスペリエンス チーム
