### ISSUE TITLE
Broken Table (host-and-deploy/proxy-load-balancer)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#341]
Broken Table
![proxy-load-balancer](https://user-images.githubusercontent.com/40815708/83939351-3085a300-a817-11ea-8ac9-72a2bbeff266.png)

https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [プロキシ サーバーとロード バランサーを使用するために ASP.NET Core を構成するConfigure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard 
I'm assigning this to you, it looks like a source issue
It only replicates in MT localized versions

**Comment by JasonCard** [comment]
Hi @hyoshioka0128 

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.


Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128 

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
