### ISSUE TITLE
Broken Table (grpc/configuration)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#343]
Broken Table
![configuration](https://user-images.githubusercontent.com/40815708/84102563-cb66c300-aa4b-11ea-8949-1bdf91593d24.png)

https://docs.microsoft.com/ja-jp/aspnet/core/grpc/configuration?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1fc8dc9f-9cc8-bda7-2cda-e9461f7c3a5d
* Version Independent ID: 85b23cfb-29a8-37f4-16f7-fdf6b0dde773
* Content: [.NET 構成のための gRPCgRPC for .NET configuration](https://docs.microsoft.com/ja-jp/aspnet/core/grpc/configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/configuration.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/grpc/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
