### ISSUE TITLE
Broken Table (blazor/supported-platforms)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#344]
Broken Table
![supported-platforms](https://user-images.githubusercontent.com/40815708/84102700-26001f00-aa4c-11ea-82f9-eb10c269e744.png)

https://docs.microsoft.com/ja-jp/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor でサポートされているプラットフォームASP.NET Core Blazor supported platforms](https://docs.microsoft.com/ja-jp/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
