### ISSUE TITLE
Broken Table (fundamentals/file-providers)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#349]
Broken Table
![file-providers](https://user-images.githubusercontent.com/40815708/84129148-8c049a80-aa7c-11ea-8c20-9aaf8ee4c609.png)

https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [ASP.NET Core でのファイル プロバイダーFile Providers in ASP.NET Core](https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
