### ISSUE TITLE
Broken Table (test/integration-tests)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#350]
Broken Table
![integration-tests](https://user-images.githubusercontent.com/40815708/84129458-ef8ec800-aa7c-11ea-9f0f-e94bc44bf7cc.png)

https://docs.microsoft.com/ja-jp/aspnet/core/test/integration-tests?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [ASP.NET Core での統合テストIntegration tests in ASP.NET Core](https://docs.microsoft.com/ja-jp/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
