### ISSUE TITLE
Broken Table (blazor/integrate-components)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#351]
Broken Table
![integrate-components](https://user-images.githubusercontent.com/40815708/84129710-45637000-aa7d-11ea-9ffe-a9323ec3d2da.png)

https://docs.microsoft.com/ja-jp/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [ASP.NET Core Razor コンポーネントを Razor Pages と MVC アプリに統合するIntegrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/ja-jp/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
