### ISSUE TITLE
Broken Table (security/anti-request-forgery)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#352]
Broken Table 
![anti-request-forgery](https://user-images.githubusercontent.com/40815708/84129900-8491c100-aa7d-11ea-8c38-fbdc80d2cc9a.png)

https://docs.microsoft.com/ja-jp/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [ASP.NET Core でのクロスサイト要求偽造 (XSRF/CSRF) 攻撃を防ぐPrevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/ja-jp/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
