### ISSUE TITLE
Broken Table (razor-pages/sdk)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#353]
Broken Table
![sdk](https://user-images.githubusercontent.com/40815708/84130086-c458a880-aa7d-11ea-86d0-e45e5fbd5366.png)

https://docs.microsoft.com/ja-jp/aspnet/core/razor-pages/sdk?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDKASP.NET Core Razor SDK](https://docs.microsoft.com/ja-jp/aspnet/core/razor-pages/sdk?view=aspnetcore-3.1)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
