### ISSUE TITLE
Broken Table (blazor/event-handling)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#354]
Broken Table
![event-handling](https://user-images.githubusercontent.com/40815708/84130284-0a157100-aa7e-11ea-8e74-d49144917cb4.png)

https://docs.microsoft.com/ja-jp/aspnet/core/blazor/event-handling?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3de31c7e-7895-9d7c-0d9a-5bdfe83b60a9
* Version Independent ID: 334b7206-d383-40c3-b346-b54df9d87293
* Content: [ASP.NET Core Blazor のイベント処理ASP.NET Core Blazor event handling](https://docs.microsoft.com/ja-jp/aspnet/core/blazor/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/event-handling.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/blazor/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

Thank you for reporting this issue.
We are aware of this issue and will update when resolved.

Best regards,
Jason
cc @CeciAc

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
