### ISSUE TITLE
Broken Table (host-and-deploy/web-farm)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#355]
Broken Table
![web-farm](https://user-images.githubusercontent.com/40815708/84130505-55c81a80-aa7e-11ea-821b-b676ec95bd59.png)

https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5be127bb-755c-98ab-d7fb-b3f50687857f
* Version Independent ID: 9562d8c0-563d-21ca-e802-80f9b99689ff
* Content: [Web ファームでの ASP.NET Core のホストHost ASP.NET Core in a web farm](https://docs.microsoft.com/ja-jp/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/web-farm.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/host-and-deploy/web-farm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @hyoshioka0128

This issue is now resolved.
Thank you for your feedback.

Best regards,
Jason
