### ISSUE TITLE
Broken Table (blazor/forms-validation)

### ISSUE THREAD

**Issue by hyoshioka0128** [dotnet/AspNetCore.Docs.ja-jp#358]
Broken Table
![forms-validation](https://user-images.githubusercontent.com/40815708/84223806-d1c17180-ab15-11ea-877e-412b874e525f.png)

https://docs.microsoft.com/ja-jp/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor のフォームと検証ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/ja-jp/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Thank you for your feedback. 


Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1

 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

 

Kind regards, 

Microsoft DOCS International Team
