### ISSUE TITLE
前提のパッケージを書いて欲しかった

### ISSUE THREAD

**Issue by satrex** [dotnet/AspNetCore.Docs.ja-jp#371]
[フィードバックをこちらに入力してください]

*以下のような記述を、冒頭に書いてほしいです。*

---

このページのコマンドを実行するには、以下のパッケージが必要です。
- Microsoft.AspNetCore.Authentication.Google

コンソールで以下のコマンドを実行し、パッケージをプロジェクトに追加します。
`dotnet add package Microsoft.AspNetCore.Authentication.Google`

---

理由：
リンクをたどれば必要パッケージがわかるのかも知れませんが、ちょっと遠すぎて迷子になりました。

特に、以下のページに誘導されてしまうと、もはや.Netの記述ではないので、
案内を外れて自力で検索しないと環境が作れない感じになります。
https://developers.google.com/identity/sign-in/web/sign-in

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [ASP.NET Core での Google 外部ログインのセットアップ](https://docs.microsoft.com/ja-jp/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Enter your feedback here]

I would like you to write the following description at the beginning.

The following packages are required to execute the commands on this page.

Microsoft.AspNetCore.Authentication.Google
Run the following command in the console to add the package to your project.
dotnet add package Microsoft.AspNetCore.Authentication.Google

Reason:
You may be able to find the required package by following the link, but I got lost a bit too far.

Especially, if you are guided to the following page, it is not a .Net description anymore,
If you do not follow the guidance and search by yourself, you will not be able to create an environment.

Please move this issue to https://github.com/dotnet/AspNetCore.Docs/issues
